import type { BattleConfig, BattleSkill, BattleUnit, QuickRule } from '../../components/BattleTestScreen';

/**
 * Debug / test encounter configuration.
 *
 * This module only contains BattleTestScreen test/tutorial encounter data.
 * Encounter stats remain debug-only. The ally skill lookup exported at the end is
 * shared with production encounters so every battle presents the same skill set.
 */

const QUICK_RULES: QuickRule[] = [
  { title: "流程", text: "每回合选择 1 个战斗技能，指定对象后立刻进入骰子判定。" },
  { title: "技能", text: "每个角色只展示 3 个战斗技能，暂不区分移动、附赠动作、反应和距离。" },
  { title: "命中", text: "攻击先投 D20，结果为骰面 + 属性/熟练/其他加值；达到目标 AC 才命中。" },
  { title: "伤害", text: "攻击命中后再投伤害骰，例如 1D8 或 2D4；未命中则行动结束。" },
];

const TUTORIAL_QUICK_RULES: QuickRule[] = [
  { title: "1 先攻", text: "战斗开始先投 1D20 + 敏捷调整值，数值越高越早行动。" },
  { title: "2 技能", text: "轮到我方时选择一个技能；本教学每名角色每回合只做一次主要行动。" },
  { title: "3 目标", text: "选好技能后指定发光目标。攻击技能打敌人，治疗技能点我方。" },
  { title: "4 结算", text: "攻击命中后才会进入伤害骰；未命中不会投伤害，也不会造成伤害。" },
];

export const BACKGROUND_URL = "/assets/battle/b1-cablestreet-battle.png";


const BATTLE_UNITS: BattleUnit[] = [
  {
    id: "pc-adventurer",
    name: "冒险者",
    faction: "ally",
    role: "战士 Lv.3 / 重装先锋",
    portrait: "冒",
    model: "adventurer",
    hp: 30,
    maxHp: 30,
    ac: 18,
    speed: 30,
    proficiency: 2,
    abilities: { str: 16, dex: 13, con: 15, int: 10, wis: 12, cha: 8 },
    weaponMastery: "长剑 Sap / 战斧 Topple / 巨剑 Graze / 长矛 Slow / 战锤 Push",
    resourceProfile: ["动作压制", "附赠恢复/控制", "反应护卫"],
    statuses: ["戒备", "板甲", "前排"],
    traits: ["HP30 / AC18", "熟练加值 +2", "战士武器精通槽位 2", "短休技能：回气、破甲连斩"],
    skills: [
      {
        id: "F1",
        name: "断筋斩",
        resource: "动作",
        source: "职业技能",
        formula: "STR + 熟练 vs AC；命中后 1d8+3 挥砍",
        effect: "命中后目标 DEX 豁免 DC13，失败则速度减半 1 轮。",
        cooldown: "无",
        rule: "攻击检定 + Topple/推撞变体",
        roll: { kind: "attack", ability: "str", targetAc: 14, label: "断筋斩命中判定" },
        tags: ["攻击", "减速", "武器精通"],
      },
      {
        id: "F2",
        name: "盾牌猛击",
        resource: "附赠动作",
        source: "职业技能",
        formula: "STR 运动 DC13；伤害 1d4+3 钝击",
        effect: "目标 STR 豁免 DC13，失败则倒地。",
        cooldown: "每战斗 2 次",
        rule: "Shove 推撞机制",
        roll: { kind: "ability", ability: "str", dc: 13, label: "盾牌猛击运动检定" },
        tags: ["检定", "倒地", "附赠动作"],
      },
      {
        id: "F3",
        name: "回气",
        resource: "附赠动作",
        source: "职业技能",
        formula: "恢复 1d8 + 战士等级",
        effect: "立即恢复生命值，用于测试治疗骰和附赠动作占用。",
        cooldown: "每次短休 1 次",
        rule: "HP 与恢复",
        roll: { kind: "healing", dieType: "d8", diceCount: 1, bonus: 3, label: "回气恢复量" },
        tags: ["治疗", "D8", "短休"],
      },
      {
        id: "F4",
        name: "嘲讽咆哮",
        resource: "附赠动作",
        source: "职业技能",
        formula: "CHA 威吓 DC14；敌人 WIS 豁免 DC13",
        effect: "15 尺内敌人失败后对你以外目标攻击受限制，持续 1 轮。",
        cooldown: "每战斗 1 次",
        rule: "Help 动作反用 + 魅惑变体",
        roll: { kind: "ability", ability: "cha", dc: 14, label: "嘲讽咆哮威吓检定" },
        tags: ["控制", "劣势", "群体"],
      },
      {
        id: "F5",
        name: "护卫拦截",
        resource: "反应",
        source: "职业技能",
        formula: "无需掷骰；5 尺内队友被攻击时触发",
        effect: "你用反应替队友承受一半伤害，伤害类型不变。",
        cooldown: "每轮 1 次",
        rule: "反应 + 半身掩护变体",
        roll: { kind: "none" },
        tags: ["反应", "护卫", "减伤"],
        trigger: "5 尺内队友被攻击",
      },
      {
        id: "F6",
        name: "破甲连斩",
        resource: "动作",
        source: "职业技能",
        formula: "STR + 熟练 vs AC，连击 2 次",
        effect: "每次命中造成武器骰+STR，两次都命中额外 1d6 挥砍。",
        cooldown: "每次短休 1 次",
        rule: "多重攻击",
        roll: { kind: "attack", ability: "str", targetAc: 18, label: "破甲连斩首击" },
        tags: ["攻击", "连击", "破甲"],
      },
      {
        id: "F7",
        name: "战争践踏",
        resource: "动作",
        source: "职业技能",
        formula: "STR 运动 DC15；范围 DEX 豁免 DC13",
        effect: "10 尺锥形，失败者倒地并受束缚 1 轮。",
        cooldown: "每次长休 1 次",
        rule: "倒地 + 束缚状态",
        roll: { kind: "ability", ability: "str", dc: 15, label: "战争践踏运动检定" },
        tags: ["范围", "倒地", "束缚"],
      },
    ],
    nonCombatSkills: [
      { name: "破门开路", check: "STR 运动 DC12-18", effect: "撞开上锁的门、栅栏或石棺。" },
      { name: "战场读势", check: "WIS 洞悉 DC14", effect: "预判伏击时先攻有优势；识破弱点后首轮攻击 +2。" },
      { name: "军械鉴定", check: "INT 调查 DC12", effect: "识别武器品质、附魔或隐藏机关。" },
      { name: "负重拖拽", check: "STR 运动 DC13", effect: "拖拽倒地队友或重物，速度减半。" },
    ],
  },
  {
    id: "ally-grum",
    name: "格鲁姆",
    faction: "ally",
    role: "矮人战士 / 铁锤破阵",
    portrait: "格",
    model: "grum",
    hp: 52,
    maxHp: 52,
    ac: 18,
    speed: 25,
    proficiency: 2,
    abilities: { str: 18, dex: 12, con: 17, int: 9, wis: 13, cha: 10 },
    weaponMastery: "战锤 Push",
    resourceProfile: ["动作击倒", "附赠临时 HP", "反应代伤"],
    statuses: ["护卫", "矮人韧性", "前排"],
    traits: ["HP52 / AC18", "战锤 1d8+4 钝击", "Push 精通", "队友专属护卫反应"],
    skills: [
      {
        id: "GM1",
        name: "裂地猛击",
        resource: "动作",
        source: "队友技能",
        formula: "STR + 熟练 vs AC；1d8+4 钝击",
        effect: "命中后目标 STR 豁免 DC15，失败倒地；近战攻击对其有优势。",
        cooldown: "无",
        rule: "攻击检定 + 倒地状态",
        roll: { kind: "attack", ability: "str", targetAc: 14, label: "裂地猛击命中判定" },
        tags: ["攻击", "倒地", "优势"],
      },
      {
        id: "GM2",
        name: "铜墙铁壁",
        resource: "附赠动作",
        source: "队友技能",
        formula: "获得 2d8 临时 HP，无需 D20",
        effect: "临时 HP 优先扣除，且下回合获得闪避效果。",
        cooldown: "每战斗 1 次",
        rule: "临时生命值 + 闪避",
        roll: { kind: "damage", dieType: "d8", diceCount: 2, bonus: 0, label: "铜墙铁壁临时 HP" },
        tags: ["临时HP", "闪避", "附赠动作"],
      },
      {
        id: "GM3",
        name: "舍身护卫",
        resource: "反应",
        source: "队友技能",
        formula: "无需掷骰；5 尺内队友被攻击时触发",
        effect: "格鲁姆完全承受该次伤害，队友受到 0 伤害。",
        cooldown: "每战斗 1 次",
        rule: "反应 + 护卫",
        roll: { kind: "none" },
        tags: ["反应", "代伤", "护卫"],
        trigger: "5 尺内队友被攻击",
      },
      {
        id: "GM4",
        name: "酒桶冲锋",
        resource: "动作",
        source: "队友技能",
        formula: "STR 运动 DC15；路径敌人 DEX 豁免 DC15",
        effect: "直线 20 尺冲刺，失败者倒地；终点对最近敌人进行一次攻击。",
        cooldown: "每次短休 1 次",
        rule: "移动 + 冲撞可选规则",
        roll: { kind: "ability", ability: "str", dc: 15, label: "酒桶冲锋运动检定" },
        tags: ["移动", "冲撞", "倒地"],
      },
    ],
    nonCombatSkills: [
      { name: "矮人石工", check: "STR 运动 +4，DC12-16", effect: "鉴定石造机关、暗门或矿脉。" },
      { name: "酒馆人脉", check: "CHA 说服 +3，DC13", effect: "打听城市传闻、黑市中介和酒馆情报。" },
      { name: "酒量比拼", check: "CON 豁免 DC15", effect: "喝倒对方套取情报，失败则自己醉酒。" },
    ],
  },
  {
    id: "ally-lisa",
    name: "丽莎",
    faction: "ally",
    role: "半精灵游荡者 / 影刃",
    portrait: "丽",
    model: "lisa",
    hp: 38,
    maxHp: 38,
    ac: 16,
    speed: 30,
    proficiency: 2,
    abilities: { str: 10, dex: 18, con: 14, int: 12, wis: 13, cha: 8 },
    weaponMastery: "短剑 Vex / 匕首 Nick",
    resourceProfile: ["动作偷袭", "附赠隐形/束缚", "反应反击"],
    statuses: ["潜行", "双持", "后排突袭"],
    traits: ["HP38 / AC16", "DEX +4", "偷袭 2d6", "Vex 命中后下击优势"],
    skills: [
      {
        id: "LS1",
        name: "暗影突袭",
        resource: "动作",
        source: "队友技能",
        formula: "DEX + 熟练 vs AC；1d6+4 + 2d6 偷袭",
        effect: "需有优势或目标 5 尺内有盟友；Vex 使下次对同目标攻击有优势。",
        cooldown: "每回合 1 次偷袭",
        rule: "偷袭 + 优势系统",
        roll: { kind: "attack", ability: "dex", targetAc: 14, label: "暗影突袭命中判定" },
        tags: ["攻击", "偷袭", "优势"],
      },
      {
        id: "LS2",
        name: "烟中恶鬼",
        resource: "附赠动作",
        source: "队友技能",
        formula: "DEX 潜行 DC15",
        effect: "成功后隐形 1 轮；本回合已造成伤害则自动成功。",
        cooldown: "每战斗 1 次",
        rule: "隐形 + 重度遮蔽",
        roll: { kind: "ability", ability: "dex", dc: 15, label: "烟中恶鬼潜行检定" },
        tags: ["隐形", "优势", "附赠动作"],
      },
      {
        id: "LS3",
        name: "暗器投网",
        resource: "附赠动作",
        source: "队友技能",
        formula: "DEX + 熟练 vs AC，射程 20/40",
        effect: "命中后目标受束缚 1 轮：速度 0、攻击劣势、被攻击优势。",
        cooldown: "每战斗 1 次",
        rule: "受束缚状态",
        roll: { kind: "attack", ability: "dex", targetAc: 14, label: "暗器投网命中判定" },
        tags: ["束缚", "远程", "附赠动作"],
      },
      {
        id: "LS4",
        name: "毒蛇反击",
        resource: "反应",
        source: "队友技能",
        formula: "DEX + 熟练 vs AC；1d4+4 穿刺 + 1d6 毒素",
        effect: "被近战攻击时对攻击者进行一次匕首反击。",
        cooldown: "每轮 1 次",
        rule: "反应攻击 + 毒素伤害",
        roll: { kind: "attack", ability: "dex", targetAc: 14, label: "毒蛇反击命中判定" },
        tags: ["反应", "反击", "毒素"],
        trigger: "丽莎被近战攻击",
      },
    ],
    nonCombatSkills: [
      { name: "拆陷大师", check: "DEX 巧手 +6，DC12-18", effect: "解除陷阱或开锁，大成功可反转陷阱。" },
      { name: "阴影潜行", check: "DEX 潜行 +6", effect: "引导队伍潜行路线，降低全队被察觉概率。" },
      { name: "暗语解读", check: "INT 调查 +4，DC14", effect: "解读盗贼黑话、暗影教会暗号或地下标记。" },
    ],
  },
  {
    id: "ally-talia",
    name: "塔莉亚",
    faction: "ally",
    role: "龙血法师学徒",
    portrait: "塔",
    model: "talia",
    hp: 24,
    maxHp: 24,
    ac: 14,
    speed: 30,
    proficiency: 2,
    abilities: { str: 8, dex: 14, con: 14, int: 17, wis: 12, cha: 13 },
    weaponMastery: "无；法术位 1级×3 / 2级×1",
    resourceProfile: ["动作法术", "反应元素抗性", "短休爆发"],
    statuses: ["奥术专注", "龙血", "远程"],
    traits: ["HP24 / AC14", "INT +3", "法术豁免 DC14", "灰烬之裔易伤变体"],
    skills: [
      {
        id: "TL1",
        name: "炽焰射线",
        resource: "动作",
        source: "队友技能",
        formula: "INT + 熟练 vs AC；1d10 火焰",
        effect: "命中后目标 DEX 豁免 DC14，失败着火，下回合开始受 1d4 火焰。",
        cooldown: "无，戏法",
        rule: "法术攻击 + 持续伤害",
        roll: { kind: "attack", ability: "int", targetAc: 14, label: "炽焰射线命中判定" },
        tags: ["法术攻击", "火焰", "持续伤害"],
      },
      {
        id: "TL2",
        name: "龙火护罩",
        resource: "反应",
        source: "队友技能",
        formula: "无需掷骰；火焰/冷冻伤害触发",
        effect: "你或 10 尺内盟友获得该伤害类型抗性，仅对本次生效。",
        cooldown: "每战斗 2 次",
        rule: "抗性：伤害减半",
        roll: { kind: "none" },
        tags: ["反应", "抗性", "减伤"],
        trigger: "受到火焰或冷冻伤害",
      },
      {
        id: "TL3",
        name: "灼热金属",
        resource: "动作",
        source: "队友技能",
        formula: "自动生效；2d8 火焰；CON 豁免 DC14",
        effect: "穿金属护甲目标失败后卸除武器/护甲，下回合无法攻击。",
        cooldown: "消耗 1级法术位",
        rule: "自动命中 + 缴械可选规则",
        roll: { kind: "save", dc: 14, targetSaveBonus: 3, label: "目标 CON 豁免" },
        tags: ["火焰", "缴械", "豁免"],
      },
      {
        id: "TL4",
        name: "龙火星爆",
        resource: "动作",
        source: "队友技能",
        formula: "15 尺锥形；DEX 豁免 DC14；3d6 火焰",
        effect: "失败全伤、成功半伤；自己受 1d4 火焰反噬。灰烬之裔伤害翻倍。",
        cooldown: "每次短休 1 次",
        rule: "范围豁免 + 易伤",
        roll: { kind: "save", dc: 14, targetSaveBonus: 3, label: "目标 DEX 豁免" },
        tags: ["范围", "火焰", "易伤"],
      },
      {
        id: "TL5",
        name: "龙息觉醒",
        resource: "动作",
        source: "队友技能",
        formula: "30 尺锥形；DEX 豁免 DC15；4d6 火焰",
        effect: "信任 > 80 且完成龙血觉醒事件后解锁，无反噬。",
        cooldown: "每次长休 1 次",
        rule: "剧情解锁技能",
        roll: { kind: "save", dc: 15, targetSaveBonus: 3, label: "目标 DEX 豁免" },
        tags: ["锁定", "范围", "火焰"],
        locked: true,
      },
    ],
    nonCombatSkills: [
      { name: "奥术译读", check: "INT 奥秘 +6，DC12-18", effect: "解读古代文字、魔法卷轴或符文。" },
      { name: "法师塔礼仪", check: "INT 历史 +4 或 CHA 说服 +3", effect: "在法师塔或学术场合获取情报。" },
      { name: "血脉共鸣", check: "被动", effect: "30 尺内感知龙类、龙血生物或龙相关魔法物品。" },
    ],
  },
  {
    id: "enemy-templar",
    name: "被腐化的圣堂骑士",
    faction: "enemy",
    role: "精英敌人 / 灰烬重甲",
    portrait: "圣",
    model: "templar",
    hp: 42,
    maxHp: 42,
    ac: 17,
    speed: 30,
    proficiency: 2,
    abilities: { str: 18, dex: 11, con: 16, int: 10, wis: 12, cha: 14 },
    weaponMastery: "巨剑 Graze / 腐化光环",
    resourceProfile: ["动作高伤", "附赠黯蚀", "反应招架"],
    statuses: ["腐化", "重甲", "首领"],
    traits: ["HP42 / AC17", "STR +4", "重甲威压", "灰烬腐化抗性"],
    skills: [
      {
        id: "ET1",
        name: "黑誓巨剑",
        resource: "动作",
        source: "敌方技能",
        formula: "STR + 熟练 vs AC；2d6+4 挥砍",
        effect: "命中后可追加 1d6 黯蚀；未命中仍可用 Graze 造成 STR 调整值伤害。",
        cooldown: "无",
        rule: "攻击检定 + Graze",
        roll: { kind: "attack", ability: "str", targetAc: 18, label: "黑誓巨剑命中判定" },
        tags: ["攻击", "黯蚀", "精通"],
      },
      {
        id: "ET2",
        name: "灰烬裁决",
        resource: "动作",
        source: "敌方技能",
        formula: "CHA 威吓 vs WIS 豁免 DC14",
        effect: "失败者恐慌 1 轮，无法主动靠近圣堂骑士。",
        cooldown: "每战斗 1 次",
        rule: "恐慌状态",
        roll: { kind: "save", dc: 14, targetSaveBonus: 1, label: "我方 WIS 豁免" },
        tags: ["控制", "恐慌", "豁免"],
      },
      {
        id: "ET3",
        name: "余烬招架",
        resource: "反应",
        source: "敌方技能",
        formula: "无需掷骰；被近战命中时触发",
        effect: "本次受到的物理伤害 -1d8，并对攻击者造成 1d4 火焰。",
        cooldown: "每轮 1 次",
        rule: "反应 + 伤害减免",
        roll: { kind: "none" },
        tags: ["反应", "减伤", "火焰"],
        trigger: "被近战攻击命中",
      },
    ],
    nonCombatSkills: [],
  },
  {
    id: "enemy-ash-a",
    name: "灰烬之影小兵A",
    faction: "enemy",
    role: "影裔爪牙 / 快速骚扰",
    portrait: "影A",
    model: "shade",
    hp: 15,
    maxHp: 15,
    ac: 13,
    speed: 35,
    proficiency: 2,
    abilities: { str: 10, dex: 16, con: 12, int: 8, wis: 11, cha: 7 },
    resourceProfile: ["动作爪击", "附赠位移", "反应撤影"],
    statuses: ["轻盈", "灰烬之裔"],
    traits: ["HP15 / AC13", "DEX +3", "速度 35 尺", "受光耀/龙火克制"],
    skills: [
      {
        id: "EA1",
        name: "暗影爪击",
        resource: "动作",
        source: "敌方技能",
        formula: "DEX + 熟练 vs AC；1d6+3 挥砍",
        effect: "命中后可向 5 尺内另一个目标施加轻度遮蔽。",
        cooldown: "无",
        rule: "近战攻击",
        roll: { kind: "attack", ability: "dex", targetAc: 16, label: "暗影爪击命中判定" },
        tags: ["攻击", "近战", "遮蔽"],
      },
      {
        id: "EA2",
        name: "烟影位移",
        resource: "附赠动作",
        source: "敌方技能",
        formula: "移动 15 尺，无需掷骰",
        effect: "不触发借机攻击，优先贴近后排。",
        cooldown: "每轮 1 次",
        rule: "移动 + 借机攻击例外",
        roll: { kind: "none" },
        tags: ["移动", "撤离", "附赠动作"],
      },
    ],
    nonCombatSkills: [],
  },
  {
    id: "enemy-ash-b",
    name: "灰烬之影小兵B",
    faction: "enemy",
    role: "影裔爪牙 / 快速骚扰",
    portrait: "影B",
    model: "shade",
    hp: 15,
    maxHp: 15,
    ac: 13,
    speed: 35,
    proficiency: 2,
    abilities: { str: 10, dex: 16, con: 12, int: 8, wis: 11, cha: 7 },
    resourceProfile: ["动作爪击", "附赠位移", "反应撤影"],
    statuses: ["轻盈", "灰烬之裔"],
    traits: ["HP15 / AC13", "DEX +3", "速度 35 尺", "受光耀/龙火克制"],
    skills: [
      {
        id: "EB1",
        name: "暗影爪击",
        resource: "动作",
        source: "敌方技能",
        formula: "DEX + 熟练 vs AC；1d6+3 挥砍",
        effect: "命中后可向 5 尺内另一个目标施加轻度遮蔽。",
        cooldown: "无",
        rule: "近战攻击",
        roll: { kind: "attack", ability: "dex", targetAc: 16, label: "暗影爪击命中判定" },
        tags: ["攻击", "近战", "遮蔽"],
      },
      {
        id: "EB2",
        name: "烟影位移",
        resource: "附赠动作",
        source: "敌方技能",
        formula: "移动 15 尺，无需掷骰",
        effect: "不触发借机攻击，优先贴近后排。",
        cooldown: "每轮 1 次",
        rule: "移动 + 借机攻击例外",
        roll: { kind: "none" },
        tags: ["移动", "撤离", "附赠动作"],
      },
    ],
    nonCombatSkills: [],
  },
];

const SIMPLE_SKILL_IDS: Record<string, string[]> = {
  "pc-adventurer": ["F1", "F6", "F3"],
  "ally-grum": ["GM1", "GM2", "GM4"],
  "ally-lisa": ["LS1", "LS3", "LS2"],
  "ally-talia": ["TL1", "TL3", "TL4"],
  "enemy-templar": ["ET1", "ET2", "ET4"],
  "enemy-ash-a": ["EA1", "EA3", "EA2"],
  "enemy-ash-b": ["EB1", "EB3", "EB2"],
};

const EXTRA_SIMPLE_SKILLS: Record<string, BattleSkill[]> = {
  "enemy-templar": [
    {
      id: "ET4",
      name: "腐化重击",
      resource: "战斗技能",
      source: "敌方技能",
      formula: "STR + 熟练 vs AC；1d8+4 黯蚀",
      effect: "命中后黯蚀能量爆开，压低我方当前生命最低者的状态。",
      cooldown: "每回合 1 次",
      rule: "简化攻击检定",
      roll: { kind: "attack", ability: "str", targetAc: 16, label: "腐化重击命中判定" },
      tags: ["攻击", "黯蚀", "压制"],
    },
  ],
  "enemy-ash-a": [
    {
      id: "EA3",
      name: "灰烬爆裂",
      resource: "战斗技能",
      source: "敌方技能",
      formula: "DEX + 熟练 vs AC；1d8+3 火焰",
      effect: "灰烬在目标身侧爆开，造成火焰伤害并制造短暂混乱。",
      cooldown: "每回合 1 次",
      rule: "简化攻击检定",
      roll: { kind: "attack", ability: "dex", targetAc: 15, label: "灰烬爆裂命中判定" },
      tags: ["攻击", "火焰", "压制"],
    },
  ],
  "enemy-ash-b": [
    {
      id: "EB3",
      name: "灰烬爆裂",
      resource: "战斗技能",
      source: "敌方技能",
      formula: "DEX + 熟练 vs AC；1d8+3 火焰",
      effect: "灰烬在目标身侧爆开，造成火焰伤害并制造短暂混乱。",
      cooldown: "每回合 1 次",
      rule: "简化攻击检定",
      roll: { kind: "attack", ability: "dex", targetAc: 15, label: "灰烬爆裂命中判定" },
      tags: ["攻击", "火焰", "压制"],
    },
  ],
};

function simplifyCombatText(text: string) {
  return text
    .replace(/，?射程\s*\d+\/\d+/g, "")
    .replace(/直线\s*\d+\s*尺/g, "冲击线")
    .replace(/\d+\s*尺锥形/g, "范围")
    .replace(/\d+\s*尺内/g, "附近")
    .replace(/\d+\s*尺/g, "近身")
    .replace(/速度\s*0/g, "行动受限")
    .replace(/速度(?:被)?减半/g, "行动受限")
    .replace(/移动\s*近身/g, "快速切入")
    .replace(/附赠动作|自由互动|反应|动作/g, "战斗技能")
    .replace(/借机攻击/g, "反制")
    .replace(/\s+/g, " ")
    .trim();
}

function normalizeSimpleSkill(skill: BattleSkill): BattleSkill {
  return {
    ...skill,
    resource: "战斗技能",
    cooldown: "每回合 1 次",
    trigger: undefined,
    formula: simplifyCombatText(skill.formula),
    effect: simplifyCombatText(skill.effect),
    rule: simplifyCombatText(skill.rule),
    tags: skill.tags.filter((tag) => !["附赠动作", "自由互动", "反应", "移动", "近战"].includes(tag)).slice(0, 4),
  };
}

function buildSimpleBattleUnit(unit: BattleUnit): BattleUnit {
  const skillIds = SIMPLE_SKILL_IDS[unit.id] ?? unit.skills.slice(0, 3).map((skill) => skill.id);
  const skillPool = [...unit.skills, ...(EXTRA_SIMPLE_SKILLS[unit.id] ?? [])];
  const skills = skillIds
    .map((skillId) => skillPool.find((skill) => skill.id === skillId))
    .filter((skill): skill is BattleSkill => Boolean(skill))
    .slice(0, 3)
    .map(normalizeSimpleSkill);

  return {
    ...unit,
    weaponMastery: unit.weaponMastery ? simplifyCombatText(unit.weaponMastery) : undefined,
    resourceProfile: ["三技能简化战斗", "不计算距离", "不区分附赠/反应"],
    traits: unit.traits.filter((trait) => !/^速度/.test(trait)).map(simplifyCombatText),
    skills,
  };
}

export const SIMPLE_BATTLE_UNITS = BATTLE_UNITS.map(buildSimpleBattleUnit);

const TUTORIAL_BATTLE_UNITS: BattleUnit[] = [
  {
    id: "tutorial-adventurer",
    name: "冒险者",
    faction: "ally",
    role: "战士 Lv.3 / 新手教学前排",
    portrait: "冒",
    model: "adventurer",
    hp: 30,
    maxHp: 30,
    ac: 18,
    speed: 30,
    proficiency: 2,
    abilities: { str: 16, dex: 13, con: 15, int: 10, wis: 12, cha: 8 },
    weaponMastery: "本场教学只保留核心概念：攻击检定、技能检定、治疗。",
    resourceProfile: ["攻击检定 vs AC", "力量检定 vs DC", "治疗恢复 HP"],
    statuses: ["前排", "教学保护"],
    traits: ["HP30 / AC18", "攻击加值会自动计算", "未命中不会造成伤害", "本场目标：把两只小怪打到 HP0"],
    skills: [
      {
        id: "TA1",
        name: "稳步斩击",
        resource: "战斗技能",
        source: "职业技能",
        formula: "STR + 熟练 vs AC；1d8+3 挥砍",
        effect: "教学重点：D20 + 力量调整值 + 熟练加值 >= 目标 AC 即命中。命中后再投伤害骰；未命中则行动结束。",
        cooldown: "每回合 1 次",
        rule: "攻击检定",
        roll: { kind: "attack", ability: "str", targetAc: 12, label: "稳步斩击命中判定" },
        tags: ["攻击", "AC", "推荐起手"],
      },
      {
        id: "TA2",
        name: "盾牌压制",
        resource: "战斗技能",
        source: "职业技能",
        formula: "STR 运动 DC12；1d4+5 钝击",
        effect: "教学重点：技能检定看 D20 + 对应属性/熟练加值 vs 固定 DC。成功会造成伤害并压低小怪攻势。",
        cooldown: "每回合 1 次",
        rule: "技能检定",
        roll: { kind: "ability", ability: "str", dc: 12, label: "盾牌压制运动检定" },
        tags: ["检定", "控制", "低风险"],
      },
      {
        id: "TA3",
        name: "回气",
        resource: "战斗技能",
        source: "职业技能",
        formula: "恢复 1d8+3 HP",
        effect: "教学重点：治疗不攻击敌人，而是选择我方目标并恢复生命值。冒险者受伤后再用最划算。",
        cooldown: "每战斗 1 次",
        rule: "治疗骰",
        roll: { kind: "healing", dieType: "d8", diceCount: 1, bonus: 3, label: "回气恢复量" },
        tags: ["治疗", "HP", "保命"],
      },
    ],
    nonCombatSkills: [],
  },
  {
    id: "ally-selin",
    name: "瑟琳",
    faction: "ally",
    role: "时间法师 / 教学支援",
    portrait: "瑟",
    model: "selin",
    hp: 24,
    maxHp: 24,
    ac: 14,
    speed: 30,
    proficiency: 2,
    initiativeBonus: 1,
    abilities: { str: 8, dex: 14, con: 12, int: 16, wis: 14, cha: 11 },
    weaponMastery: "固定同行；负责讲解法术攻击、豁免和治疗。",
    resourceProfile: ["法术攻击 vs AC", "迫使目标豁免", "队友治疗"],
    statuses: ["后排", "奥术支援", "时间感"],
    traits: ["HP24 / AC14", "INT +3", "法术 DC13", "光亮会压制裂隙爬兽"],
    skills: [
      {
        id: "SE1",
        name: "银钟光束",
        resource: "战斗技能",
        source: "队友技能",
        formula: "INT + 熟练 vs AC；1d8+3 光耀",
        effect: "教学重点：法术攻击也使用 D20 + 施法属性 + 熟练加值。裂隙爬兽怕光，命中后很容易进入残血。",
        cooldown: "每回合 1 次",
        rule: "法术攻击",
        roll: { kind: "attack", ability: "int", targetAc: 12, label: "银钟光束命中判定" },
        tags: ["法术攻击", "光耀", "补刀"],
      },
      {
        id: "SE2",
        name: "星轨震荡",
        resource: "战斗技能",
        source: "队友技能",
        formula: "INT + 熟练 vs AC；2d4 奥术",
        effect: "命中后对敌方全体造成 2d4 奥术伤害，主目标额外受到 2 点伤害。",
        cooldown: "每回合 1 次",
        rule: "范围法术攻击",
        roll: { kind: "attack", ability: "int", targetAc: 12, label: "星轨震荡命中判定" },
        tags: ["法术攻击", "范围", "全体", "奥术"],
        primaryTargetBonus: 2,
      },
      {
        id: "SE3",
        name: "逆钟愈合",
        resource: "战斗技能",
        source: "队友技能",
        formula: "恢复 1d8+3 HP",
        effect: "教学重点：治疗可以点冒险者或瑟琳。新手战斗里敌方伤害较低，治疗主要用于理解 HP 变化。",
        cooldown: "每战斗 2 次",
        rule: "治疗骰",
        roll: { kind: "healing", dieType: "d8", diceCount: 1, bonus: 3, label: "逆钟愈合恢复量" },
        tags: ["治疗", "支援", "安全网"],
      },
    ],
    nonCombatSkills: [],
  },
  {
    id: "tutorial-crawler-a",
    name: "裂隙爬兽A",
    faction: "enemy",
    role: "小怪 / 爪击教学",
    portrait: "爬A",
    model: "crawler",
    hp: 28,
    maxHp: 28,
    ac: 12,
    speed: 25,
    proficiency: 2,
    abilities: { str: 8, dex: 14, con: 12, int: 4, wis: 10, cha: 5 },
    resourceProfile: ["低伤害攻击", "怕光", "被击败即退出战斗"],
    statuses: ["惊慌", "怕光", "教学敌人"],
    traits: ["HP28 / AC12", "DEX +2", "伤害已降低", "随机选择攻击目标"],
    skills: [
      {
        id: "CR1A",
        name: "畏光爪击",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "DEX + 熟练 vs AC；1d4+2 挥砍",
        effect: "小怪最基础的攻击：投 D20 加敏捷和熟练，对比目标 AC。命中也只造成少量伤害。",
        cooldown: "每回合 1 次",
        rule: "敌方攻击检定",
        roll: { kind: "attack", ability: "dex", targetAc: 16, label: "畏光爪击命中判定" },
        tags: ["攻击", "低伤害", "教学"],
      },
      {
        id: "CR2A",
        name: "孢尘喷吐",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "无需命中；所有敌对目标 1d4 毒素",
        effect: "小怪吐出浅绿色孢尘，对所有敌对目标造成 1D4 毒素伤害，不进行命中或豁免。",
        cooldown: "每回合 1 次",
        rule: "自动群体伤害",
        roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 0, label: "孢尘喷吐伤害" },
        tags: ["群体", "毒素", "自动命中"],
      },
      {
        id: "CR3A",
        name: "惊慌缩伏",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "无需掷骰；小怪生命过低时缩成一团",
        effect: "用于教学怪物行为：弱小敌人不会死战到底，HP 归 0 前也会出现畏惧和退缩。",
        cooldown: "剧情表现",
        rule: "行为提示",
        roll: { kind: "none" },
        tags: ["行为", "怕光", "撤退"],
      },
    ],
    nonCombatSkills: [],
  },
  {
    id: "tutorial-crawler-b",
    name: "裂隙爬兽B",
    faction: "enemy",
    role: "小怪 / 群体伤害教学",
    portrait: "爬B",
    model: "crawler",
    hp: 28,
    maxHp: 28,
    ac: 12,
    speed: 25,
    proficiency: 2,
    abilities: { str: 8, dex: 14, con: 12, int: 4, wis: 10, cha: 5 },
    resourceProfile: ["自动群体伤害", "怕光", "被击败即退出战斗"],
    statuses: ["惊慌", "孢尘", "教学敌人"],
    traits: ["HP28 / AC12", "自动命中", "伤害已降低", "用孢尘展示群体伤害"],
    skills: [
      {
        id: "CR2B",
        name: "孢尘喷吐",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "无需命中；所有敌对目标 1d4 毒素",
        effect: "教学重点：敌人也会使用自动群体伤害技能。所有我方角色都会受到 1D4 毒素伤害，无需命中或豁免。",
        cooldown: "每回合 1 次",
        rule: "自动群体伤害",
        roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 0, label: "孢尘喷吐伤害" },
        tags: ["群体", "毒素", "自动命中"],
      },
      {
        id: "CR1B",
        name: "畏光爪击",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "DEX + 熟练 vs AC；1d4+2 挥砍",
        effect: "基础爪击，主要用于展示 AC 的防护价值。冒险者 AC18 很难被命中，瑟琳 AC14 会更危险。",
        cooldown: "每回合 1 次",
        rule: "敌方攻击检定",
        roll: { kind: "attack", ability: "dex", targetAc: 16, label: "畏光爪击命中判定" },
        tags: ["攻击", "低伤害", "教学"],
      },
      {
        id: "CR3B",
        name: "惊慌缩伏",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "无需掷骰；被光照或重击压制时退缩",
        effect: "用于教学战斗叙事：敌人行为会根据伤势和恐惧改变，KP 描写会体现骰点结果。",
        cooldown: "剧情表现",
        rule: "行为提示",
        roll: { kind: "none" },
        tags: ["行为", "怕光", "撤退"],
      },
    ],
    nonCombatSkills: [],
  },
  {
    id: "tutorial-crawler-c",
    name: "裂隙爬兽C",
    faction: "enemy",
    role: "小怪 / 轮转教学",
    portrait: "爬C",
    model: "crawler",
    hp: 28,
    maxHp: 28,
    ac: 12,
    speed: 25,
    proficiency: 2,
    abilities: { str: 8, dex: 14, con: 12, int: 4, wis: 10, cha: 5 },
    resourceProfile: ["混合方式", "怕光", "展示多目标轮转"],
    statuses: ["惊慌", "畏光", "教学敌人"],
    traits: ["HP28 / AC12", "DEX +2", "伤害已降低", "展示三对多回合轮转"],
    skills: [
      {
        id: "CR1C",
        name: "畏光爪击",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "DEX + 熟练 vs AC；1d4+2 挥砍",
        effect: "连续小怪攻击展示多回合压力：看看瑟琳是否需要治疗",
        cooldown: "每回合 1 次",
        rule: "敌方攻击检定",
        roll: { kind: "attack", ability: "dex", targetAc: 16, label: "畏光爪击命中判定" },
        tags: ["攻击", "低伤害", "教学"],
      },
      {
        id: "CR2C",
        name: "孢尘喷吐",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "无需命中；所有敌对目标 1d4 毒素",
        effect: "配合其他小怪攻击，让我方全体承受 1D4 毒素伤害，以展示治疗的重要性。",
        cooldown: "每回合 1 次",
        rule: "自动群体伤害",
        roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 0, label: "孢尘喷吐伤害" },
        tags: ["群体", "毒素", "自动命中"],
      },
      {
        id: "CR3C",
        name: "惊慌缩伏",
        resource: "战斗技能",
        source: "敌方技能",
        formula: "无需掷骰；同伴被击败后更加畏缩",
        effect: "展示怪物在劣势下行为改变：同伴倒下的恐慌会蔓延。",
        cooldown: "剧情表现",
        rule: "行为提示",
        roll: { kind: "none" },
        tags: ["行为", "怕光", "撤退"],
      },
    ],
    nonCombatSkills: [],
  },
];

/* 测试战斗阵容：冒险者+瑟琳 vs 三只裂隙爬兽（与教学配置相同） */
const TEST_BATTLE_UNITS: BattleUnit[] = [
  {
    id: "test-adventurer", name: "冒险者", faction: "ally", role: "战士 Lv.3", portrait: "冒", model: "adventurer",
    hp: 30, maxHp: 30, ac: 18, speed: 30, proficiency: 2,
    abilities: { str: 16, dex: 13, con: 15, int: 10, wis: 12, cha: 8 },
    resourceProfile: ["攻击", "检定", "治疗"], statuses: ["前排"], traits: ["HP30/AC18"],
    skills: [
      { id: "T1", name: "稳步斩击", resource: "战斗技能", source: "职业技能", formula: "STR+熟练 vs AC；1d8+3", effect: "基础攻击", cooldown: "每回合1次", rule: "攻击检定", roll: { kind: "attack", ability: "str", targetAc: 12, label: "稳步斩击" }, tags: ["攻击"] },
      { id: "T2", name: "盾牌压制", resource: "战斗技能", source: "职业技能", formula: "STR运动 DC12；1d4+5", effect: "技能检定", cooldown: "每回合1次", rule: "技能检定", roll: { kind: "ability", ability: "str", dc: 12, label: "盾牌压制" }, tags: ["检定"] },
      { id: "T3", name: "回气", resource: "战斗技能", source: "职业技能", formula: "恢复1d8+3", effect: "治疗自身", cooldown: "每战斗1次", rule: "治疗骰", roll: { kind: "healing", dieType: "d8", diceCount: 1, bonus: 3, label: "回气" }, tags: ["治疗"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-selin", name: "瑟琳", faction: "ally", role: "时间法师", portrait: "瑟", model: "selin",
    hp: 24, maxHp: 24, ac: 14, speed: 30, proficiency: 2, initiativeBonus: 1,
    abilities: { str: 8, dex: 14, con: 12, int: 16, wis: 14, cha: 11 },
    resourceProfile: ["法术攻击", "豁免", "治疗"], statuses: ["后排"], traits: ["HP24/AC14"],
    skills: [
      { id: "S1", name: "银钟光束", resource: "战斗技能", source: "队友技能", formula: "INT+熟练 vs AC；1d8+3光耀", effect: "法术攻击", cooldown: "每回合1次", rule: "法术攻击", roll: { kind: "attack", ability: "int", targetAc: 12, label: "银钟光束" }, tags: ["法术"] },
      { id: "S2", name: "星轨震荡", resource: "战斗技能", source: "队友技能", formula: "INT+熟练 vs AC；2d4奥术", effect: "命中后对敌方全体造成2d4奥术伤害，主目标额外受到2点伤害。", cooldown: "每回合1次", rule: "范围法术攻击", roll: { kind: "attack", ability: "int", targetAc: 12, label: "星轨震荡命中判定" }, tags: ["法术攻击", "范围", "全体", "奥术"], primaryTargetBonus: 2 },
      { id: "S3", name: "逆钟愈合", resource: "战斗技能", source: "队友技能", formula: "恢复1d8+3", effect: "治疗队友", cooldown: "每战斗2次", rule: "治疗骰", roll: { kind: "healing", dieType: "d8", diceCount: 1, bonus: 3, label: "逆钟愈合" }, tags: ["治疗"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-senluo", name: "布洛克", faction: "ally", role: "矮人·铁锅战士", portrait: "布", model: "senluo",
    hp: 48, maxHp: 48, ac: 16, speed: 25, proficiency: 2,
    abilities: { str: 16, dex: 12, con: 16, int: 10, wis: 14, cha: 8 },
    resourceProfile: ["攻击", "治疗", "范围"], statuses: ["前排"], traits: ["HP48/AC16", "矮人韧性"],
    skills: [
      { id: "SN1", name: "铁锅猛击", resource: "战斗技能", source: "队友技能", formula: "STR+熟练 vs AC；1d8+3钝击", effect: "命中可眩晕", cooldown: "每回合1次", rule: "攻击检定", roll: { kind: "attack", ability: "str", targetAc: 14, label: "铁锅猛击" }, tags: ["攻击"] },
      { id: "SN2", name: "矮人炖汤", resource: "战斗技能", source: "队友技能", formula: "恢复2d6+3", effect: "治疗队友", cooldown: "每战斗2次", rule: "治疗骰", roll: { kind: "healing", dieType: "d6", diceCount: 2, bonus: 3, label: "矮人炖汤" }, tags: ["治疗"] },
      { id: "SN3", name: "辣椒炸弹", resource: "战斗技能", source: "队友技能", formula: "范围DEX豁免DC14；2d6火焰", effect: "范围火焰+目盲", cooldown: "每战斗1次", rule: "范围豁免", roll: { kind: "save", dc: 14, targetSaveBonus: 2, label: "辣椒炸弹" }, tags: ["范围"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-ailin", name: "艾琳", faction: "ally", role: "精灵·生命牧师", portrait: "艾", model: "ailin",
    hp: 28, maxHp: 28, ac: 14, speed: 30, proficiency: 2,
    abilities: { str: 8, dex: 14, con: 13, int: 12, wis: 18, cha: 15 },
    resourceProfile: ["治疗", "祝福", "护盾"], statuses: ["后排"], traits: ["HP28/AC14", "治疗+2"],
    skills: [
      { id: "AL1", name: "生命之光", resource: "战斗技能", source: "队友技能", formula: "恢复2d8+4", effect: "治疗+解控", cooldown: "每回合1次", rule: "治疗骰", roll: { kind: "healing", dieType: "d8", diceCount: 2, bonus: 4, label: "生命之光" }, tags: ["治疗"] },
      { id: "AL2", name: "神圣祝福", resource: "战斗技能", source: "队友技能", formula: "友方AC+1，临时HP 1d4+2", effect: "祝福队友，提供临时防护", cooldown: "每战斗3次", rule: "友方增益", roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 2, label: "神圣祝福临时HP" }, tags: ["增益", "祝福", "临时HP"] },
      { id: "AL3", name: "白枝护盾", resource: "战斗技能", source: "队友技能", formula: "友方AC+2，临时HP 2d6", effect: "白枝光盾护住队友", cooldown: "每战斗2次", rule: "友方护盾", roll: { kind: "damage", dieType: "d6", diceCount: 2, bonus: 0, label: "白枝护盾临时HP" }, tags: ["护盾", "增益", "临时HP"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-kelaiya", name: "凯娅", faction: "ally", role: "猫人·怪物猎人", portrait: "凯", model: "kelaiya",
    hp: 34, maxHp: 34, ac: 15, speed: 35, proficiency: 2,
    abilities: { str: 10, dex: 18, con: 12, int: 13, wis: 14, cha: 10 },
    resourceProfile: ["偷袭", "拆陷阱", "撤退"], statuses: ["潜行"], traits: ["HP34/AC15", "偷袭2d6"],
    skills: [
      { id: "KL1", name: "猫爪突袭", resource: "战斗技能", source: "队友技能", formula: "DEX+熟练 vs AC；1d6+4+2d6偷袭", effect: "潜行偷袭", cooldown: "每回合1次", rule: "偷袭", roll: { kind: "attack", ability: "dex", targetAc: 14, label: "猫爪突袭" }, tags: ["攻击"] },
      { id: "KL2", name: "陷阱拆除", resource: "战斗技能", source: "队友技能", formula: "DEX巧手DC14", effect: "拆除+反伤", cooldown: "每战斗2次", rule: "技能检定", roll: { kind: "ability", ability: "dex", dc: 14, label: "陷阱拆除" }, tags: ["反伤"] },
      { id: "KL3", name: "烟幕撤退", resource: "战斗技能", source: "队友技能", formula: "制造烟雾", effect: "遮蔽脱离", cooldown: "每战斗1次", rule: "遮蔽", roll: { kind: "none" }, tags: ["遮蔽"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-crawler-a", name: "裂隙爬兽A", faction: "enemy", role: "小怪", portrait: "爬A", model: "crawler",
    hp: 28, maxHp: 28, ac: 12, speed: 25, proficiency: 2,
    abilities: { str: 8, dex: 14, con: 12, int: 4, wis: 10, cha: 5 },
    resourceProfile: ["攻击", "群体伤害"], statuses: ["怕光"], traits: ["HP28/AC12"],
    skills: [
      { id: "CA1", name: "畏光爪击", resource: "战斗技能", source: "敌方技能", formula: "DEX+熟练 vs AC；1d4+2", effect: "近战攻击", cooldown: "每回合1次", rule: "攻击检定", roll: { kind: "attack", ability: "dex", targetAc: 16, label: "畏光爪击" }, tags: ["攻击"] },
      { id: "CA2", name: "孢尘喷吐", resource: "战斗技能", source: "敌方技能", formula: "无需命中；全体敌对目标 1d4毒素", effect: "自动群体伤害", cooldown: "每回合1次", rule: "自动伤害", roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 0, label: "孢尘喷吐伤害" }, tags: ["群体", "毒素", "自动命中"] },
      { id: "CA3", name: "惊慌缩伏", resource: "战斗技能", source: "敌方技能", formula: "剧情表现", effect: "受伤后退缩", cooldown: "剧情", rule: "行为", roll: { kind: "none" }, tags: ["行为"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-crawler-b", name: "裂隙爬兽B", faction: "enemy", role: "小怪", portrait: "爬B", model: "crawler",
    hp: 28, maxHp: 28, ac: 12, speed: 25, proficiency: 2,
    abilities: { str: 8, dex: 14, con: 12, int: 4, wis: 10, cha: 5 },
    resourceProfile: ["群体伤害", "攻击"], statuses: ["孢尘"], traits: ["HP28/AC12"],
    skills: [
      { id: "CB1", name: "孢尘喷吐", resource: "战斗技能", source: "敌方技能", formula: "无需命中；全体敌对目标 1d4毒素", effect: "自动群体伤害", cooldown: "每回合1次", rule: "自动伤害", roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 0, label: "孢尘喷吐伤害" }, tags: ["群体", "毒素", "自动命中"] },
      { id: "CB2", name: "畏光爪击", resource: "战斗技能", source: "敌方技能", formula: "DEX+熟练 vs AC；1d4+2", effect: "近战攻击", cooldown: "每回合1次", rule: "攻击检定", roll: { kind: "attack", ability: "dex", targetAc: 16, label: "畏光爪击" }, tags: ["攻击"] },
      { id: "CB3", name: "惊慌缩伏", resource: "战斗技能", source: "敌方技能", formula: "剧情表现", effect: "被压制后退缩", cooldown: "剧情", rule: "行为", roll: { kind: "none" }, tags: ["行为"] },
    ], nonCombatSkills: [],
  },
  {
    id: "test-crawler-c", name: "裂隙爬兽C", faction: "enemy", role: "小怪", portrait: "爬C", model: "crawler",
    hp: 28, maxHp: 28, ac: 12, speed: 25, proficiency: 2,
    abilities: { str: 8, dex: 14, con: 12, int: 4, wis: 10, cha: 5 },
    resourceProfile: ["混合"], statuses: ["畏光"], traits: ["HP28/AC12"],
    skills: [
      { id: "CC1", name: "畏光爪击", resource: "战斗技能", source: "敌方技能", formula: "DEX+熟练 vs AC；1d4+2", effect: "近战攻击", cooldown: "每回合1次", rule: "攻击检定", roll: { kind: "attack", ability: "dex", targetAc: 16, label: "畏光爪击" }, tags: ["攻击"] },
      { id: "CC2", name: "孢尘喷吐", resource: "战斗技能", source: "敌方技能", formula: "无需命中；全体敌对目标 1d4毒素", effect: "自动群体伤害", cooldown: "每回合1次", rule: "自动伤害", roll: { kind: "damage", dieType: "d4", diceCount: 1, bonus: 0, label: "孢尘喷吐伤害" }, tags: ["群体", "毒素", "自动命中"] },
      { id: "CC3", name: "惊慌缩伏", resource: "战斗技能", source: "敌方技能", formula: "剧情表现", effect: "同伴倒下后畏缩", cooldown: "剧情", rule: "行为", roll: { kind: "none" }, tags: ["行为"] },
    ], nonCombatSkills: [],
  },
];

const TEST_BATTLE_CONFIG: BattleConfig = {
  units: TEST_BATTLE_UNITS,
  quickRules: QUICK_RULES,
  eyebrow: "COMBAT SANDBOX",
  title: "战斗测试",
  subtitle: "冒险者+瑟琳+布洛克+艾琳+凯娅 vs 三只裂隙爬兽",
  backLabel: "返回测试",
  rerollLog: "重新进行全员 1D20 先攻判定。",
  initialLog: "战斗测试初始化：5名我方 + 3名敌方，选技能、指定对象、掷骰结算。",
  initiativeNote: "8位单位同时1D20判定：D20 + 敏捷调整值 + 其他加值。",
  winTitle: "战斗测试胜利",
  loseTitle: "战斗测试失败",
  winText: "三只裂隙爬兽已失去战斗能力，测试完成。",
  loseText: "我方全部失去战斗能力，可重投先攻重新测试。",
};

const TUTORIAL_BATTLE_CONFIG: BattleConfig = {
  units: TUTORIAL_BATTLE_UNITS,
  quickRules: TUTORIAL_QUICK_RULES,
  eyebrow: "FIRST COMBAT TUTORIAL",
  title: "补给平台教学战斗",
  subtitle: "冒险者与瑟琳对抗三只裂隙爬兽：先学先攻、攻击、豁免、治疗，再继续主线。",
  backLabel: "返回剧情",
  rerollLog: "教学战斗重置：重新投先攻，并恢复冒险者、瑟琳和三只裂隙爬兽的 HP。",
  initialLog: "新手教学开始：先看教学说明，再投先攻；本场重点是理解流程。",
  initiativeNote: "5 位单位同时进行 1D20 判定：D20 + 敏捷调整值 + 其他加值。数值最高者先行动。",
  winTitle: "教学战斗胜利",
  loseTitle: "教学战斗失败",
  winText: "三只裂隙爬兽已经失去战斗能力。你掌握了先攻、攻击、自动伤害、治疗和回合推进。",
  loseText: "本场是教学战斗，可以重投先攻重新练习；敌人伤害较低，优先让冒险者承伤。",
  completeLabel: "继续剧情",
  tutorialIntro: {
    title: "瑟琳的战斗教学",
    subtitle: "依次掌握先攻检定、技能施放、目标选择与防御站位。本场为保证教学流畅度预设为必胜，重心在于理解回合制战斗的每一层判据。",
    steps: [
      { title: "① 先攻", text: "开场所有单位投 1D20 + 敏捷调整值。行动条从左到右显示顺序，当前行动者高亮。" },
      { title: "② 选择技能", text: "轮到你时点下方技能，选攻击（稳步斩击）、检定（盾牌压制）或治疗（回气）。" },
      { title: "③ 指定目标", text: "选完技能后，敌对单位会发光。点击目标确认释放，攻击打敌人，治疗点我方。" },
      { title: "④ 观察骰子", text: "右侧弹出 3D 骰子展示 D20 结果和加值 vs 目标AC/DC，看清通过还是失败再点继续。" },
      { title: "⑤ 防御站位", text: "冒险者 AC 较高，适合顶在前排承受主要火力；瑟琳 AC 偏低，应保持在后方施法与治疗。高 AC 单位承伤是基础战术构成。" },
      { title: "⑥ 治疗时机", text: "回气和逆钟愈合恢复 HP。受伤后用治疗维持血量，不要等 HP 过低才动手。" },
    ],
    enemySkills: [
      { name: "裂隙爬兽A", skills: ["畏光爪击：D20 + 敏捷 vs AC，低伤害近战。", "孢尘喷吐：无需命中，所有敌对目标受到 1D4 毒素。", "惊慌缩伏：展示怪物受伤后的退缩行为。"] },
      { name: "裂隙爬兽B", skills: ["孢尘喷吐：优先展示自动群体伤害。", "畏光爪击：展示瑟琳 AC 较低、前排更适合承伤。", "惊慌缩伏：被光照或重击压制时会畏缩。"] },
      { name: "裂隙爬兽C", skills: ["畏光爪击：多只小怪轮番攻击，体会回合交替的压力。", "孢尘喷吐：毒素持续消耗我方全体血量，治疗的重要性。", "惊慌缩伏：同伴倒下后更加畏缩。"] },
    ],
  },
};

export type BattleDebugMode = "test" | "tutorial" | "side-event";

export function getBattleConfig(mode: BattleDebugMode = "test"): BattleConfig {
  return mode === "tutorial" ? TUTORIAL_BATTLE_CONFIG : TEST_BATTLE_CONFIG;
}

/**
 * Keep party abilities identical from the tutorial through every story battle.
 * Adventurer/Serin use the tutorial definitions; companions use the full-party
 * definitions because they are recruited after the tutorial encounter.
 */
export function getSharedPartySkills(model: string): BattleSkill[] | undefined {
  const source = model === "adventurer" || model === "selin"
    ? TUTORIAL_BATTLE_UNITS
    : TEST_BATTLE_UNITS;
  const unit = source.find((candidate) => candidate.faction === "ally" && candidate.model === model);
  return unit?.skills.map((skill) => ({
    ...skill,
    roll: { ...skill.roll },
    tags: [...skill.tags],
  }));
}

