import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frontendRoot = path.resolve(__dirname, '..');
const assetsRoot = path.join(frontendRoot, 'public', 'assets');
const outputFile = path.join(frontendRoot, 'src', 'data', 'generated', 'galleryManifest.ts');

const IMAGE_EXTS = new Set(['.png', '.jpg', '.jpeg', '.webp', '.gif', '.svg']);
const AUDIO_EXTS = new Set(['.mp3', '.wav', '.ogg']);
const VIDEO_EXTS = new Set(['.mp4', '.webm']);
const SUPPORTED_EXTS = new Set([...IMAGE_EXTS, ...AUDIO_EXTS, ...VIDEO_EXTS]);

const TITLE_OVERRIDES = {
  '/assets/scenes/12lain-survivor-site.webp': '第三远征队遗弃营地',
  '/assets/scenes/10blue-shoal-after-battle.webp': '蓝伞浅滩战后',
  '/assets/scenes/12yunling-apothecary.webp': '云苓药铺',
};

function walk(dir) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  return entries.flatMap((entry) => {
    if (entry.name.startsWith('.')) return [];
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) return walk(fullPath);
    if (!entry.isFile()) return [];
    return [fullPath];
  });
}

function toPublicPath(fullPath) {
  return `/assets/${path.relative(assetsRoot, fullPath).replaceAll(path.sep, '/')}`;
}

function mediaType(ext) {
  if (IMAGE_EXTS.has(ext)) return 'image';
  if (AUDIO_EXTS.has(ext)) return 'audio';
  if (VIDEO_EXTS.has(ext)) return 'video';
  return 'unknown';
}

function category(publicPath, ext) {
  const lower = publicPath.toLowerCase();
  if (AUDIO_EXTS.has(ext)) return 'audio';
  if (VIDEO_EXTS.has(ext)) return 'video';
  if (/\/(scenes|backgrounds|bg)\//.test(lower)) return 'scene';
  if (/\/(cg|ending|story)\//.test(lower)) return 'cg';
  if (/\/(characters|portraits|npcs)\//.test(lower)) return 'character';
  if (/\/(chibi|sprites)\//.test(lower)) return 'chibi';
  if (/\/(enemies|enemy|monsters)\//.test(lower)) return 'enemy';
  if (/\/items\//.test(lower) || /\/icons\/items\//.test(lower)) return 'item';
  if (/\/(buildings|locations)\//.test(lower)) return 'building';
  if (/\/ui\//.test(lower) || /\/icons\/ui\//.test(lower)) return 'ui';
  if (/\/(maps|battle-maps)\//.test(lower)) return 'map';
  return 'other';
}

function titleFromFile(fileName, publicPath) {
  if (TITLE_OVERRIDES[publicPath]) return TITLE_OVERRIDES[publicPath];
  const base = fileName.replace(/\.[^.]+$/, '');
  return base
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function slug(value) {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function buildManifest() {
  if (!fs.existsSync(assetsRoot)) return [];
  return walk(assetsRoot)
    .map((fullPath) => {
      const ext = path.extname(fullPath).toLowerCase();
      if (!SUPPORTED_EXTS.has(ext)) return null;
      const publicPath = toPublicPath(fullPath);
      const rel = path.relative(assetsRoot, fullPath).replaceAll(path.sep, '/');
      const fileName = path.basename(fullPath);
      const folder = rel.split('/')[0] || '';
      const tags = rel.split('/').slice(0, -1).filter(Boolean);
      const itemCategory = category(publicPath, ext);
      return {
        id: `${itemCategory}-${slug(rel.replace(/\.[^.]+$/, ''))}`,
        title: titleFromFile(fileName, publicPath),
        path: publicPath,
        category: itemCategory,
        mediaType: mediaType(ext),
        ext,
        fileName,
        folder,
        tags,
        sortKey: `${itemCategory}/${rel.toLowerCase()}`,
      };
    })
    .filter(Boolean)
    .sort((a, b) => a.sortKey.localeCompare(b.sortKey, 'zh-Hans-CN'));
}

const manifest = buildManifest();
const output = `// This file is generated by frontend/scripts/buildGalleryManifest.mjs.
// Do not edit manually; add assets under frontend/public/assets and rerun the script.
import type { GalleryAsset } from '../../features/gallery/galleryTypes';

export const galleryManifest: GalleryAsset[] = ${JSON.stringify(manifest, null, 2)};
`;

fs.mkdirSync(path.dirname(outputFile), { recursive: true });
fs.writeFileSync(outputFile, output, 'utf8');
console.log(`galleryManifest generated: ${manifest.length} assets`);

